/*
 * This source file was generated by the Gradle 'init' task
 */
package test.java.org.codegym;

import org.junit.Test;
import static org.junit.Assert.*;

import org.codegym.application.App;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
